#+TITLE: Energy World Building
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>

* Energy
** Basic Energy Rules
All energy requires the user to channel it to be, used. Most energies require both arms to be free for the elbow down.
*** Energy points (ep)
Some energies require (ep) to use (there are: Life, Kinetic, Time, Matter). Energy points is; stored, named, measured and, regained differently for each energy. The energies that don't use (ep) simply manipulate the already excising energy in the world.   
*** Energy Devices and Crystals
Energy is a form of power and it obeys the [[https://en.wikipedia.org/wiki/First_law_of_thermodynamics][first law of thermodynamics]] energy crystals are natural deposits of energy most of witch act as batteries as such they can be discharged and then recharged (only can be recharged by a user of the same energy as the crystal). These crystals can be used to power different devices that then can do actions similar to use energy but at a much lower efficacy.    

** Energy Types
| Color  | Name      | Description                                                                                                           |
|--------+-----------+-----------------------------------------------------------------------------------------------------------------------|
| Purple | Ethereal  | Allows the user to either create portals a short distance away or either retrieve or deposed an item into the Either. |
| Black  | Life/Dark | Gives the user the ability to both drain and restore life from a willing/broken living object.                        |
| Yellow | Kinetic   | Turns the users caloric energy into kinetic energy witch can be, directed towards any thing in sight (max:100m).      |
| White  | Fusing    | Grants the user the ability to combine and control the energy of willing/unconscious channeled energy users.          |
| Pink   | Mind      | Can see and manipulate for a (ep) cost the Mind-web.                                                                  |
| Green  | Time      | Gives the user the ability to glide theme selves and any items on there person thru time for a cost of (ep).          |
| Orange | The Ohoou | The Ohoou is a energy based hive mind although individuals or groups of individuals my be separated form the central hive mind. |
| Blue   | Matter    | The user has the ability to change the state of matter at will.                                                                 |

*** Ethereal (Purple)
Ethereal energy allows the user to either create portals (max 2m diameter) a short distance away or either retrieve or deposed an item (witch can fit into the hand) into the Either.

**** Level Table
Each Level there are the options two different please only pick one.
| Level        | Opt 1      | Opt 2                                                |
|--------------+------------+------------------------------------------------------|
| Natural      | +1m^3 Hold | +5m Portal Range                                     |
| Novice       | +1m^3 Hold | +10m Portal Range                                    |
| Intermediate | +1m^3 Hold | +10m Portal Range                                    |
| Master       | +2m^3 Hold | +15m Portal Range                                    |
| High Master  | +3m^3 Hold | +500m Portal Range                                   |
| Grand Master | +5m^3 Hold | +1k Portal Range and Pick one former unpicked option |

*** Life/Dark (Black)
 Life energy gives the user the ability to both drain and restore life from a willing/broken entity with life force. The draining of life force restores (ep) while the restoring to others and performing energy actions depletes (ep). For dark energy users the total depletion of (ep) is lethal having low (ep) has negative side effects on the wielder (chart below).

**** Level Table
The ability you choose must be at most of the same level as your creator.
| Level        |                                                            |
|--------------+------------------------------------------------------------|
| Natural      | +1,000 Dark energy Holding +1 Dark ability                 |
| Novice       | +1,000 Dark energy Holding +1 Dark ability                 |
| Intermediate | +3,000 Dark energy Holding +1 Dark ability                 |
| Master       | +5,000 Dark energy Holding +1 Dark ability                 |
| High Master  | +10,000 Dark energy Holding +1 Dark ability                |
| Grand Master | +50,000 Dark energy Holding +1 Dark ability and Dark sight |
**** Dark Ability Table
To use a ability you must be at lest the same level as the ability. 
| Level        | Name                | Description                                                                                                                         |
|--------------+---------------------+-------------------------------------------------------------------------------------------------------------------------------------|
| Natural      | Dark Energy Control | The user can control up to you max capacity of Dark energy capacity while its in a physical form. (50^3cm = 1,000 Dark(ep))         |
| Novice       | Force Drain         | This allows the user to forcefully drain a targets Life energy (within sight) but at the expense of (2x) the life energy drained.   |
| Novice       | Dark Speak          | Allows the user to speed Dark crystals.                                                                                             |
| Intermediate | Will Brake          | Whom ever uses this is able to brake the will of a creature. This allows draining. (Costs creatures (Str+End+Int-Age)x10 + 3 hours) |
| Intermediate | Energy whips        | Allows you to control as much energy as you like assuming it is in contact with your arms. (Damage ((ep) in whips x .01)D )         |
| Master       | Energy Tentacles    | Control four tentacles on any size as long as there connected to you. at HM the number increase to five an GM eight.                |
| Grand Master | Dark sight          | Allows you the see the total Dark and not Dark (ep) where ever you look                                                             |
**** Energy Point Loss table
| Energy Points | Effect           |
|---------------+------------------|
| 500+ (ep)     | N/A              |
| 499-300 (ep)  | -1 End DM        |
| 299-100 (ep)  | -1 To all roles  |
| 99-50 (ep)    | -5 To all roles  |
| 49 - 1 (ep)   | -10 To all roles |
| 0 (ep)        | Death            |

*** Kinetic (Yellow)
 Turns the users caloric energy into kinetic energy witch can be, directed towards any thing in sight (max:100m). The amount of (ep) the user has stored is, deterred by the users stored caloric energy witch is a 1:1 ration to (ep) but, only one third of the caloric intake can be, used for energy the other 2/3 are, used for normal body functions.

**** Level Table
| Level        |                                                  |
|--------------+--------------------------------------------------|
| Natural      | +100N Max Force                                  |
| Novice       | +100N Max Force                                  |
| Intermediate | +300N Max Force                                  |
| Master       | +500N Max Force                                  |
| High Master  | +10,00N Max Force                                |
| Grand Master | +30,00N Max Force can and control unseen objects |

*** Fusing (White)
Grants the user the ability to combine and control the energy of willing/unconscious channeled energy users. Allowing the to do fused abilities up to the users level.

**** Level Table
| Level        |                                                                                   |
|--------------+-----------------------------------------------------------------------------------|
| Natural      | +2 Source fuse max                                                                |
| Novice       | +3 Source fuse max                                                                |
| Intermediate | +5 Source fuse max                                                                |
| Master       | +10 Source fuse max                                                               |
| High Master  | +30 Source fuse max                                                               |
| Grand Master | +50 Source fuse max and can channel and learn to control the energy for a crystal of all types |

**** Fused Energy Abilities Table
| Level        | Energies        | Name       | Description                                                                                                                                     |
|--------------+-----------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------|
| Intermediate | Ethereal & Life | Black hole | Forms a black hole (max 2m Diameter) that sucks the life energy out of anyone in a 1k radius.                                                   |
| Intermediate | Kinetic & Life  | Life Steal | For the cost of 3x Dark (ep) and 10 Kinetic (ep)/min file Force drain is instant and has a pushily effect on any one within a 1m of the victim. |
|              |                 |            |                                                                                                                                                 |

*** Mind (Pink)
Can see and manipulate for a (ep) cost the Mind-web. the Mind-web is both the web of ideas in ones mind as well as the web of ideas amongst individuals and groups. Energy points must be used to do any manipulations to find the (ep) cost multiply the group size by the manipulation size to get the total (ep) cost. Mind energy is gained by daring minds of one the user has killed this will permanently leave the user with this persons memories witch will lead to insanity of time as well as loss of ones selfie.    

**** Level Table
| Level        |                                                                                      |
|--------------+--------------------------------------------------------------------------------------|
| Natural      | Can only see the web on a individual level and can't manipulate it.                  |
| Novice       | Can only see the web on a individual level and can only do small manipulations it.   |
| Intermediate | Can only see the web on a Small Group level and can only do small manipulations it.  |
| Master       | Can only see the web on a Small Group level and can only do medium manipulations it. |
| High Master  | Can only see the web on a Large Group level and can only do medium manipulations it. |
| Grand Master | Can see the web on a total level and can do Large manipulations it.                  |
***** Groups Sizes
| Size       | Number of people | (ep) cost |
|------------+------------------+-----------|
| Individual |                1 |         1 |
| Small      |               10 |         5 |
| Large      |              100 |        10 |
| Total      |              All |        15 |
***** Manipulation sizes
| Size   |                               | (ep) cost |
|--------+-------------------------------+-----------|
| Small  | A detail                      |         1 |
| Medium | Multiple details up to five   |         5 |
| Large  | Total fabrication of a memory |        10 |

*** Time (Green)
Gives the user the ability to glide theme selves and any items on there person thru time for a cost of (ep), But either traveling too fast or to far can have severe side effects in the forum of uncontrollable displacement thru time. Whilst traveling thru time the user will NOT be move in position relative the nearest gravitational body of ant lest 3/10G . 

**** Level Table
For jumps larger than the max safe time refer the function blow.
| Level        |                       |
|--------------+-----------------------|
| Natural      | Max safe travel 5m.   |
| Novice       | Max safe travel 15m.  |
| Intermediate | Max safe travel 25m.  |
| Master       | Max safe travel 30m.  |
| High Master  | Max safe travel 60m.  |
| Grand Master | Max safe travel 100m. |
***** Jump distance function
This is used to both find and, represent how to find the random variation in time energy time travel.    

#+BEGIN_SRC python :results output
  import random

  timeJumped = 5 #Change to the Time being jumped.
  level = 0 #Change to current level Nat:0, Nov:1, Int:2, Ma:3, Hm:4 and, Gm:5.
  doLastJumpCalc = False # Do you whant to do the last jump calc? true = yes false = no
  timeSinceLastJump = 0 # How long has it been since the last jump?
  lastJumpDistance = 0 # How long was your last jump?

  def levelMax(level):
	    if level == 0 : return 5
	    elif level == 1 : return 15
	    elif level == 2 : return 25
	    elif level == 3 : return 30
	    elif level == 4 : return 60
	    elif level == 5 : return 100
	    else: return 5

  def timeJumpedOver(timeJumped,level):
	    timeJumpedOver = timeJumped - levelMax(level)
	    if timeJumped < 0: return 0
	    else: return timeJumpedOver

  def timeJumpedOverPercentage(timeJumped,level,doLastJumpCalc,timeSinceLastJump,lastJumpDistance):
	    if(doLastJumpCalc == True and lastJumpDistance > timeSinceLastJump and timeSinceLastJump != 0):
		      return timeJumped/(levelMax(level) - (lastJumpDistance - timeSinceLastJump))
	    elif timeSinceLastJump == 0: return 1
	    else: return timeJumped/levelMax(level)

  def jumpedBackDistance(level,timeJumped,timeJumpedOver,doLastJumpCalc,timeSinceLastJump,lastJumpDistance):
	    if levelMax(level) == timeJumped and doLastJumpCalc == False: return timeJumped
	    elif timeJumpedOverPercentage(timeJumped,level,doLastJumpCalc,timeSinceLastJump,lastJumpDistance) <= 1: return timeJumped + random.uniform(levelMax(level)*1, levelMax(level)*2) 
	    elif timeJumpedOverPercentage(timeJumped,level,doLastJumpCalc,timeSinceLastJump,lastJumpDistance) <= 2: return timeJumped + random.uniform(levelMax(level)*2, levelMax(level)*4) 
	    elif timeJumpedOverPercentage(timeJumped,level,doLastJumpCalc,timeSinceLastJump,lastJumpDistance) <= 3: return timeJumped + random.uniform(levelMax(level)*3, levelMax(level)*5) 
	    elif timeJumpedOverPercentage(timeJumped,level,doLastJumpCalc,timeSinceLastJump,lastJumpDistance) <= 5: return timeJumped + random.uniform(levelMax(level)*4, levelMax(level)*6)
	    else: return -1


  def printOutput(level,timeJumped,timeJumpedOverPercentage,doLastJumpCalc,timeSinceLastJump,lastJumpDistance):
	    print("Jumped", jumpedBackDistance(level,timeJumped,timeJumpedOver,doLastJumpCalc,timeSinceLastJump,lastJumpDistance), "minutes back in time.")
  printOutput(level,timeJumped,timeJumpedOverPercentage,doLastJumpCalc,timeSinceLastJump,lastJumpDistance)
#+END_SRC

#+RESULTS:
: Jumped 5 minutes back in time.

*** The Ohoou (Orange) 
The Ohoou is a energy based hive mind although segments/individuals or groups of individuals my be separated form the central hive mind. Normal this is a willing possess of the Ohoou but, at times of unknown reason a segment my be unwilling separated this segment will maintain all information stored within it this may only enough to maintain life or the full ability for the segment to operate independently. Dependent on the circumstances of separation the segment my or my not be able to ever reconnect to the central hive mined.    

*** Matter (Blue)
The user has the ability to change the [[https://en.wikipedia.org/wiki/List_of_states_of_matter][states of matter]] at will of object with in 5m radios. This power does come a cost tho costing one (ep) for ever 1/4cm^3 of matter. As well as they can not put matter in to state that can not be in. Energy points are storied in the body ad it natural energy and can be replenished by eating where one (ep) is equal to 1500 kilo calories.

* Items
** Weapons
Naming conventions Martian:M### UN:EDF### <Name> WC:Country/### CE:The_Grate <Name> SS:<Leader>-###
Type Designations Rail-gun:RG Lazier:LZ Propellant:PP
Effective range is for earth like conditions.         
*** Ranged
**** M172 RG
2D + 1, 20 R, 2R/S, ER 30m
**** EDF103 Sandy PP
3D + 2, 10 R, 1R/S, ER 100m
**** WCUS/184 RG
1D, 320 R, 15R/S, ER 30m
**** The_Grate Liberator PP
1D + 2, 10 R, 1R/S, ER 20m
**** SS_PeterI-798 LZ
***** Charge Blast
6D, 2 R, (1/5)R/S, ER ∞
***** Normal Blast
2D, 100 R, 1 R/S, ER ∞

*** Melee  
** Energy Devices
*** Weapons
**** Ac3-702-BM
The Ac3 as it's commonly known is a handheld energy focuser (beam diameter of 3cm). The Ac3 is powered by any energy crystal from a (ep) based energy. It conceits of a metallic black or gray shell if the shape of a pistol, but towards the back at a 45° tilted away form the barrel a cylindrical out cropping where small energy crystal is placed to power the device. Pressing the trigger will activate the device in ether Normal or inverted modes. Dependent on the state of the selector switch.       

*DO NOT ATTEMPT TO USE WITH CRYSTAL ABOVE OR AT 100°C THIS MY END IN DEATH FOR ALL IN A 5M RADIOS OF THE Ac3-702-BM!*

***** Life    
With Life energy it is able to move 500(ep)/m.
****** Normal mode
It fires a direct beam of consecrated energy injecting life energy into whom ever it hits. 
****** Inverted mode
It fires a direct beam of consecrated energy execrating life energy into whom ever it hits. This causes a 50% inefficient witch is out put as heat increasing the temperature of 10°c/30s during use.  
***** Kinetic 
****** Normal mode
Creates a beam of energy that pushes away any thing it touches at or near [[https://en.wikipedia.org/wiki/Speed_of_light][light speed]] this causes the crystal to heat up by 10°c/15s.  
****** Inverted mode
Creates a beam of energy that pulls any thing it touches at or near [[https://en.wikipedia.org/wiki/Speed_of_light][light speed]] this causes the crystal to heat up by 10°c/15s.  
***** Time
****** Normal mode
The Ac3 will move it's self to a random point in time forward. 
****** Inverted mode
The Ac3 will move it's self to a random point in time backward. 
***** Matter
****** Normal mode
Causes any thing the beam touches to kill turn into gas it its already gas it will turn into plasma. This will cause the crystal to heat up by 100°c/s.    
****** Inverted mode
Causes any thing the beam touches to kill turn into liquid it its already liquid it will turn into solid. This will cause the crystal to heat up by 100°c/s.
    
** Tools
** Drugs
*** Class A
*** Class B
*** Class C
** Ships
Naming conventions Martian:M###<Ship Class> UN:EDF###Space <Name> WC:Country/###S CE:The_Grate <Name> SS:-Yuri Gagarin-### BO:Boeing 9##
*** Transport
**** M882LrTrans
Diameter 15m
| Deck(s) # |                                                |
|-----------+------------------------------------------------|
|         0 | Bridge                                         |
|         1 | Mess/Armory                                    |
|         2 | Crew Quarters                                  |
|       3-5 | 1m wide corridor one either side passer rooms. |
|         6 | Docking                                        |
|       7,8 | Engineering                                    |
*** Cargo/Freighters
**** Boeing 977
Diameter 100m until deck 5 then 20m.
| Deck(s) # |               |
|-----------+---------------|
|         0 | Docking       |
|       1-5 | Cargo         |
|         6 | Mess/Armory   |
|         7 | Crew Quarters |
|         8 | Bridge        |
|         9 | Engineering   |

** Ship Weapons
* Timeline
** The Start of WWIII 
*** 2020
+ China broke a agreement with the UK surrounding Hong Kong.
+ Chines ships show growing hostility towards American, British, German, and Japanese ships in the sea of Japan.
*** 2026
+ Independent Chines pirates take a German cargo ship hostage. The chines government responds by drooping a bomb on the deck of the cargo ship. Before nearby American or German troops can respond; ending in the deaths of all 30 crew members and the lost a the 1.6B Euros Ship and the 460M Euros in cargo.
+ The German Public is in out rage. Angela Merkel makes a public statement damming the chines government in the actions.
+ The German war machine starts ramping up.
*** 2028
+ The Chines government asks the United States to retract all units from nine-dash line. The United States refuses.
+ The /USS Harry S. Truman/ is sunk of the cost off Taiwan after a air and sea skirmish with China.
Casualties
CCP: 3,426
US: 1,548
DE: 164
UK: 34
TW: 4
+ US Present John W. Nicholson. Declares war on China. Germany follows suit.
+ Queen Elizabeth II voices support for the US and Germany.
*** 2029
+ Prince Philips plain is shot down by the Chines while on a culinary visit to Japan.
+ British prime minster Jon L. Smith is force to resign under growing presser.
+ British PM Edward H. Smith declares war on China. Pulling the entire common wealth in.
+ Quebec's PM Éttienne Napoleon voices anti English sentiment.
** WWIII
*** Factions
| Allies        | China |
|---------------+-------|
| US            | CCP   |
| UK            |       |
| SA            |       |
| CA            |       |
| AU            |       |
| NZ            |       |
| HK            |       |
| DE            |       |
| RU (March 31) |       |
| MN (April 31) |       |
*** 2030
+ A British lead multinational coalition lays siege to Hong Kong capturing in 36 hours.
+ Riots erupt in tanimania square.
+ Germany pushes into Shenzhen
*** 2031
+ China responds with a 30mil string push. Germany falls back to Hong Kong where the Allies hold
**** The Siege of Hong Kong    
***** February 
+ The Allies are pushed back to Ma Wan
+ China drops bombs on Kap Shui Mun Bridge cutting the Allies forward healed position on Ma Wan off from the main base and airfield on Tung Chung.
+ China attempts a push from Chines held Tsing Yi down Tsing Ma Bridge to the Allies forward base on Ma Wan. The chines end up building a barricade out of there own fallen troops. Loosing 330,845 men.
+ At the same time as the push China launches conventional ICBMs at Washington, New York, London, Berlin, Munich. The ICBMs headed for North America are stopped by American defines systems and the one headed for Europe are stopped by the Russian defines systems.
***** March                
+ Over air space violations Russia declares war on China.
+ US spy plains capture images of 85mill chines troops moving towards Hong Kong.
+ 2mill Allie troops are evacuated to Taiwan from Chek Lap Kok. 132,023 men are lost in heavy carpet bombing of Tung Chug by China.
Casualties Allies 312,513 China 8,234,493
**** Post Siege of Hong Kong 
+ Under Russian Mongolia joins the Allies
+ A joint Moscow Mi16 task force starts establishing insurgency groups inside Hohhot, Beijing, and Hong Kong.
*** 2032
+ Various minor sea battles  
Casualties Allies 2,891 China 332,451
+ The Start of the [[Taiwanese Civil War][Taiwanese Civil War]]
**** December
+ Russian sleeper cells are activated in Beijing.
+ Xi Jinping is assisted by a Russian agent.
+ Mi16/Moscow insurgency groups are activated.
*** 2033   
+ Hohhot and Hong Kong are under insurgent control.
+ A Russian lead joint Russian Mongolian coalition capture Inner Mongolia.
+ German troop move into Hong Kong. Insurgents are at first hesitant of Germans until a peace offering of German bear and sausage.
*** 2034        
+ China Pops
+ Most unseeded nuclear arms are launcher randomly. Most are stopped by either Russian or American defines systems, but not all nukes land in Munich, Paris, Glasgow, Las Angeles, New York, Tokyo, and Sidney.
*** Land Captured      
| Land           | New Owner      |
|----------------+----------------|
| Hong Kong      | United Kingdom |
| Inner Mongolia | Mongolia       |
| Tibet          | American Tibet |
| Macao          | Germany        |
*** Total Casualties 
| Country | Military | Civilian   |
|---------+----------+------------|
| US      | 42,231   | 23,433,137 |
| UK      | 38,231   | 611,748    |
| DE      | 29,872   | 1,538,302  |
| RU      | 126,231  | 6          |
| MN      | 3,212    | 987        |
| FR      | 842      | 2,148,271  |
| AZ      | 2,023    | 5,312,163  |
| JP      | 231      | 13,929,280 |
*** Taiwanese Civil War  
**** 2032
***** October
+ Protest in Taipei over the so called western occupation of Taiwan.
***** November
+ Riots in Tainan
+ US Army military police use lethal crowd control tactics in Tainan.
***** December   
+ A man in Yilan City rapes a German female troop. Her company with out orders for high command responds with the massacre of the man and his family.
+ Anti western riots start in Taipei, Tainan, Yilan City, and Kaohsiung. 
+ Allie troops are attacked by locals while on liberty. 
+ Taiwanese president Li Xiu Lee formally expels Allie troops. The Allies refuse.
+ The US sees control of Taipei. Much of the government including Li Xiu Lee flees to Japan; where Japanese offices arrest them on behalf of the US. There promptly sentenced to Death in Japanese courts.
**** 2033 
***** January       
+ The US establish a puppet government and takes control of the rest of the island.
***** April 
+ The frequency of riots increases to the point where the puppet government lethally enforces a curfew kills the internet and jams all radio transitions.
***** June       
+ A full scale rebellion has started 
+ Allies retreat troops to either Japan or there homeland.
***** July
+ The puppet government falls to the totalitarian up rising.   
** The Nuclear Winter  
*** 2033
+ Global tempers are reduced by on average 5°c.  
+ A multi national task force by the name of SEANCTF (South East Asian Nuclear Capture Task Force) comprised of The UK, The US, France, Germany, and Russia is assailed to capture any remaining nuclear weapons in the south east Asian war zone formally known as china.
*** 2034
+ Famine in Poland
+ The UK declares war on Iceland over fishing rights.
+ The US pays the UK in salmon to end the war.
*** 2037
+ Poverty rate in Spain is at 98%
+ Poland devolves into anarchy
*** 2040
+ [[The war of Iberia][The war of Iberia]] starts.
*** 2045 
+ The US and UK form the Western Collision
+ Canada joins the WC 
*** 2050 
+ France leaves the EU joining the WC
*** 2051
+ German leaves the EU joining the WC
+ The [[https://en.wikipedia.org/wiki/European_Space_Agency][esa]] headquarters in Paris are raided by French authorities
+ The remnants of the [[https://en.wikipedia.org/wiki/European_Space_Agency][esa]], the [[https://en.wikipedia.org/wiki/Canadian_Space_Agency][CSA]], the [[https://en.wikipedia.org/wiki/UK_Space_Agency][UKSA]], and [[https://en.wikipedia.org/wiki/NASA][NASA]] are combined to forum the WCSA.      
*** The war of Iberia    
**** 2040
+ Spain brakes in to a civil war
**** 2043
+ West Spain attacks Portugal, The UK and Germany respond to help.
+ The UK blockades Spanish ports while Germany rolls tanks thru the country.
+ The Fall of East Spain to German Hands.
+ The Fall of West Spain to German and British hands.
**** Land Captured   
| Land                                  | New Owner      |
|---------------------------------------+----------------|
| North Spanish Coast                   | United Kingdom |
| South Spanish Coast West of Gibraltar | United Kingdom |
| The rest of Spain                     | German Iberia  |
|                                       |                |
*Going to put some more stuff up there ^ but for now I'm going to work on some latter events*
*** 2263 
* Factions
** Earth
*** Major
**** Western Collision
***** Leaders
+ United States of America
+ English Commonwealth
+ German Empire
+ French Republic
***** Members 
+ The Northern Lights
+ German Iberia 
+ Flanders
+ Luxembourg
+ Belgium
+ Austria
+ Liechtenstein
+ Hungary
+ West Poland
+ Iceland
+ Greenland
+ Quebec
+ Mexico 
+ Israel
+ Greece
+ Turkey
+ American Istanbul
+ Japan
**** The Chines Empire
***** Leader
+ China
***** Members
+ Taiwan
+ Korea
+ Vietnam
+ Laos
+ Cambodia
+ Mongolia 
+ Kyrgyzstan 
+ Philippines
+ Brazil
**** The Slavic States 
***** Leader
+ Russia 
***** Members
+ Kazakhstan
+ Ukraine
+ Belarus
+ Lithuania
+ Latvia 
+ Estonia
+ Yugoslavia
+ Romania
+ Moldova
+ Czechia
+ Slovakia
*** Minor 
**** English Commonwealth
**** Switzerland 
***** Leaders
+ The Crown
+ England 
+ Scotland
+ Whales
+ Ireland
***** Members 
+ Canada
+ Australia
+ New Zealand
+ Singapore
+ Hong Kong
+ New South Africa
+ English Nigeria
** Mars

** Belt
